# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: silth.fhir.terminology.core
canonical: https://terms.sil-th.org/core
version: 0.1.1
name: SilTHTerminology
title: SIL-TH Terminology (STU1)
status: active
publisher:
  name: Standards and Interoperability Lab - Thailand (SIL-TH)
  url: https://www.sil-th.org
description: A terminology registry which an be cited by FHIR artifacts
license: CC0-1.0
fhirVersion: 5.0.0
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2023+
releaseLabel: trial-use

pages:
  index.md:
    title: SIL-TH Terminology
  identifier-systems.md:
    title: รวม Identifier Systems

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Identifier Systems: identifier-systems.html
  Artifacts Summary: artifacts.html
