// From external terminology
Alias: $SCT = http://snomed.info/sct
Alias: $ICD10 = http://hl7.org/fhir/sid/icd-10
Alias: $ICD9CM = http://terminology.hl7.org/CodeSystem/icd9cm
Alias: $LNC = http://loinc.org
Alias: $UCUM = http://unitsofmeasure.org
Alias: $ISO3166 = urn:iso:std:iso:3166
Alias: $ISCO08 = urn:oid:2.16.840.1.113883.2.9.6.2.7
Alias: $ISO4217 = urn:iso:std:iso:4217
Alias: $ICDO3 = http://terminology.hl7.org/CodeSystem/icd-o-3
Alias: $EDQM = http://standardterms.edqm.eu
