CodeSystem: CS_THCC_RehabServiceType
Id: cs-thcc-rehab-service-type
Title: "THCC: รหัสบริการฟื้นฟูสภาพ"
Description: "รหัสบริการฟื้นฟูสภาพ โดย THCC (ID: 162)"
* ^url = $CS_THCC_RehabServiceType
* #5501421 "Intermittent traction, cervical" "การดึงคอด้วยเครื่องดึงแบบไม่ต่อเนื่อง"
* #5501422 "Static traction, cervical" "การดึงคอด้วยการถ่วงน้ำหนักต่อเนื่อง"
* #5521421 "Intermittent traction, lumbar" "การดึงหลังด้วยเครื่องดึงแบบไม่ต่อเนื่อง"
* #5521422 "Static traction, lumber" "การดึงหลังด้วยการถ่วงน้ำหนักต่อเนื่อง"
* #5849651 "Back school training" "การฝึกการใช้หลังในการเคลื่อนไหวให้ถูกต้อง"
* #6001711 "Stump bandaging, upper extremity" "การพันตอแขนที่ขาดด้วยผ้ายืด"
* #6001712 "Pneumatic compression (e.g. Jobst), upper extremity" "เครื่องรีดลดบวมจากน้ำเหลืองคั่งด้วยแรงดันลม ที่แขน"
* #6001713 "Elastic stocking, upper extremity" "การให้การรักษาด้วยถุงสวมผ้ายืดที่ตอแขน"
* #7269652 "Hand function training" "การฝึกการทำงานของมือ"
* #7311711 "Stump bandaging, lower extremity" "การพันตอขาที่ขาดด้วยผ้ายืด"
* #7311712 "Pneumatic compression (e.g. Jobst), lower extremity" "เครื่องรีดลดบวมด้วยแรงดันลม ที่ขา"
* #7311713 "Elastic stocking, lower extremity" "การให้การรักษาด้วยถุงสวมผ้ายืดที่ตอขา"
* #9000010 "Medical Rehabilitation assessment and evaluation" "การตรวจประเมินและการประเมินผลด้านเวชศาสตร์ฟื้นฟู"
* #9000011 "Impairment and Disability assessment and evaluation" "การตรวจประเมินและการประเมินผลความบกพร่องและความด้อยสมรรถภาพ"
* #9000012 "Functional activity assessment and evaluation" "การตรวจประเมินและการประเมินผลความสามารถทำกิจกรรมที่มีการเคลื่อนไหว"
* #9000013 "Neurodevelopmental assessment and evaluation" "การตรวจประเมินและการประเมินผลการพัฒนาการทางระบบประสาทและสมอง"
* #9000015 "Musculoskeletal assessment and evaluation" "การตรวจประเมินและการประเมินผลระบบกระดูกและกล้ามเนื้อ"
* #9000016 "Cardiac and pulmonary rehabilitation assessment and evaluation" "การตรวจประเมินและการประเมินผลด้านเวชศาสตร์ฟื้นฟูโรคหัวใจและโรคปอด"
* #9000017 "Communication and Speech assessment and evaluation" "การตรวจประเมินและการประเมินผลความสามารถด้านการสื่อสารและการพูด"
* #9000021 "Assessment of body structure and function for prosthetic and orthotic prescription" "การตรวจประเมินความพร้อมและการทำงานของส่วนของร่างกายที่ต้องใส่อุปกรณ์พยุงหรือกายอุปกรณ์เทียม เพื่อสั่งอุปกรณ์"
* #9000022 "Psychosocial assessment and evaluation" "การตรวจประเมินและการประเมินผลด้านจิตสังคมวิทยา"
* #9000023 "Prevocational and vocational assessment and evaluation" "การตรวจประเมินและการประเมินผลความพร้อมด้านอาชีพและการทำงาน"
* #9000029 "Rehabilitation assessment and evaluation, unspecified" "การตรวจประเมินและการประเมินผลด้านเวชศาสตร์ฟื้นฟูอื่นๆ, ไม่ระบุรายละเอียด"
* #9000030 "Medical rehabilitation certification, for disablement by rehabilitation act" "การออกเอกสารใบรับรองความพิการ เพื่อใช้สิทธิ พ.ร.บ. คนพิการ"
* #9000031 "Medical rehabilitation certification, for impairment by other laws" "การออกเอกสารใบรับรองการสูญเสียความสามารถ เพื่อใช้สิทธิ พ.ร.บ. กองทุนเงินทดแทน"
* #9000039 "Medical certification, unspecified" "พ.ร.บ. กองทุนเงินทดแทน"
* #9000202 "Exercise stress test" "การทดสอบวัดด้วย Exercise stress test"
* #9000203 "Aerobic fitness capacity standard methods" "การทดสอบวัดสมรรถภาพร่างกายด้านแอโรบิคด้วยวิธีมาตรฐาน"
* #9000204 "Aerobic fitness capacity alternative methods (submaximum or indirect exercise testing)" "การทดสอบวัดสมรรถภาพร่างกายด้านแอโรบิคด้วยวิธีทดแทน"
* #9000205 "Anaerobic fitness capacity" "การทดสอบวัดสมรรถภาพร่างกายด้านแอนแอโรบิค"
* #9000206 "Muscle strength testing using special sport equipment" "การทดสอบความแข็งแรงของกล้ามเนื้อด้วยอุปกรณ์หรือเครื่องมือเฉพาะ"
* #9000207 "Muscle strength testing using isokinetic machine" "การทดสอบความแข็งแรงของกล้ามเนื้อด้วยเครื่องไอโซคิเนติก"
* #9000208 "Muscle power testing using special sport equipment" "การทดสอบความมีพลังของกล้ามเนื้อด้วยอุปกรณ์หรือเครื่องมือเฉพาะ"
* #9000209 "Flexibility testing" "การทดสอบความยืดหยุ่น"
* #9000210 "Response time testing" "การทดสอบความไวในการตอบสนอง"
* #9000211 "Biodynamic analysis" "การตรวจวิเคราะห์ทางด้านการเคลื่อนไหว"
* #9000212 "Gait analysis using observation" "การตรวจวิเคราะห์การเดินจากท่าเดิน"
* #9000213 "Gait analysis using motion analysis" "การตรวจวิเคราะห์การเดินด้วยอุปกรณ์วิเคราะห์การเคลื่อนไหว"
* #9000214 "Lung vital capacity" "การตรวจวัดความจุปอด"
* #9000215 "Body composition measurement" "การตรวจวิเคราะห์องค์ประกอบร่างกาย"
* #9000216 "Anthropometric measurement" "การตรวจวัดขนาดและสัดส่วนของร่างกายจากภายนอก"
* #9000299 "Physical test, using other devices or techniques, unspecified" "การตรวจทดสอบทางกายภาพโดยใช้เครื่องมืออื่นๆ, ไม่ระบุรายละเอียด"
* #9001001 "Acupuncture with electrical stimulation" "การฝังเข็มแผนจีนร่วมกับเครื่องกระตุ้นไฟฟ้า"
* #9001002 "Acupuncture without electrical stimulation" "การฝังเข็มแผนจีนไม่ใช้เครื่องกระตุ้นไฟฟ้า"
* #9001003 "Acupuncture with moxibustion" "การฝังเข็มแผนจีนร่วมกับการรมสมุนไพรจีน"
* #9001004 "Acupuncture using cupping" "การฝังเข็มแผนจีนร่วมกับการครอบถ้วยสูญญากาศ"
* #9001499 "Immobilize or traction device, unspecified" "การดึงหรือดามให้อยู่นิ่งด้วยเครื่องมือหรืออุปกรณ์, ไม่ระบุ"
* #9001500 "Massage, at any site and whole body" "การนวด, ไม่ระบุตำแหน่งหรืออัวยวะ"
* #9001501 "Acupressure at any site and whole body" "การรักษาด้วยการฝังเข็ม ไม่ระบุตำแหน่งหรืออัวยวะ หรือทั้งตัว"
* #9001799 "Compressive device, unspecified" "อุปกรณ์ที่ใช้ในการกดรัดรีดอื่นๆ, ไม่ระบุ"
* #9005601 "Shortwave diathermy" "การบำบัดรักษาด้วยเครื่องให้ความร้อนลึกด้วยคลื่นสั้น"
* #9005602 "Microwave diathermy" "การบำบัดรักษาด้วยเครื่องให้ความร้อนลึกด้วยคลื่นไมโครเวฟ"
* #9005603 "Ultrasound therapy" "การบำบัดรักษาด้วยเครื่องให้ความร้อนลึกด้วยคลื่นเสียงอัลตราซาวด์"
* #9005604 "Extracorporial Shock Wave therapy" "การบำบัดรักษาด้วยเครื่องคลื่นเสียงสั่นกระแทก"
* #9005605 "Hydroculator (Hot pack)" "การบำบัดรักษาด้วยแผ่นให้ความร้อนไฮดรอคูลเลเตอร์"
* #9005606 "Paraffin wax bath" "การบำบัดรักษาด้วยขี้ผึ้งพาราฟิน"
* #9005607 "Laser therapy" "การบำบัดรักษาด้วยเลเซอร์"
* #9005608 "UV lamp therapy" "การบำบัดรักษาด้วยแสงยูวี"
* #9005609 "Infrared lamp therapy" "การบำบัดรักษาด้วยแสงอินฟราเรด"
* #9005699 "Hyperthermic therapy at local region, unspecific device" "การบำบัดรักษาด้วยเครื่องมือทำให้ความร้อนเฉพาะส่วนของร่างกายอื่นๆ, ไม่ระบุรายละเอียด"
* #9005701 "Cold pack therapy" "การบำบัดรักษาด้วยแผ่นให้ความเย็น"
* #9005709 "Cryotherapy, using unspecific device" "การบำบัดรักษาด้วยความเย็นด้วยอุปกรณ์/เครื่องมือชนิดอื่นๆ, ไม่ระบุรายละเอียด"
* #9005911 "Whirlpool therapy" "การบำบัดรักษาด้วยสระน้ำวน"
* #9005912 "Hubbard tank therapy" "การบำบัดด้วยอ่างฮับบาร์ด"
* #9005913 "Contrast bath therapy" "การบำบัดด้วยการใช้อ่างสลับร้อนและเย็น"
* #9005919 "Hydrotherapy, unspecific device" "ธาราบำบัดชนิดต่างๆ, ไม่ระบุรายละเอียด"
* #9005985 "Music therapy" "ดนตรีบำบัด"
* #9005986 "Recreational therapy" "นันทนาการบำบัด"
* #9009501 "Medical rehabilitation counseling" "การให้คำปรึกษาปัญหาสุขภาพด้านเวชศาสตร์ฟื้นฟู"
* #9009502 "Impairment and Disability counseling" "การให้คำปรึกษาด้านความบกพร่องและการไร้ความสามารถ"
* #9009503 "Functional activity counseling" "การให้คำปรึกษาปัญหาในการเคลื่อนไหวเพื่อทำกิจกรรมต่างๆ"
* #9009504 "Neurodevelopmental counseling and education" "การให้คำปรึกษาและให้ความรู้ปัญหาการพัฒนาทางระบบประสาท"
* #9009505 "Neuromuscular counseling and education" "การให้คำปรึกษาและให้ความรู้ปัญหาการพัฒนาทางระบบประสาทและกล้ามเนื้อ"
* #9009506 "Musculoskeletal pain counseling and education" "การให้คำปรึกษาและให้ความรู้ของอาการเจ็บปวดระบบกระดูกและกล้ามเนื้อ"
* #9009507 "Cardiac and pulmonary rehabilitation counseling and education" "การให้คำปรึกษาและให้ความรู้ปัญหาด้านเวชศาสตร์ฟื้นฟูโรคหัวใจและโรคปอด"
* #9009508 "Communication and speech counseling and education" "การให้คำปรึกษาและให้ความรู้ปัญหาการสื่อสาร, การพูดและการใช้ภาษา"
* #9009509 "Psychological counseling" "การให้คำปรึกษาและให้ความรู้ปัญหาด้านจิตใจ"
* #9009510 "Prosthetic and orthotic counseling and education" "การให้คำปรึกษาและให้ความรู้ปัญหาของอุปกรณ์พยุงและอวัยวะเทียม"
* #9009511 "Social worker counseling" "การให้คำปรึกษาด้านสังคมสงเคราะห์"
* #9009512 "Prevocational and vocational counseling" "การให้คำปรึกษาด้านการฝึกกิจกรรมเตรียมความพร้อมและฝึกอาชีพ"
* #9009513 "Care-giver counseling and education" "การให้คำปรึกษาและให้ความรู้ผู้ดูแลผู้ป่วย"
* #9009514 "Recreational therapy counseling and education" "การให้คำปรึกษาและให้ความรู้ด้านนันทนาการบำบัด"
* #9009515 "Protective behavior counseling and education" "การให้คำปรึกษาและให้ความรู้ด้านการปรับเปลี่ยนพฤติกรรมเพื่อลดการบาดเจ็บ"
* #9009599 "Rehabilitation counseling and education, unspecified"
* #9009681 "Activity of Daily Living (ADL) training" "การฝึกกิจกรรมที่ต้องใช้ในชีวิตประจำวัน"
* #9009682 "Prevocational training" "การฝึกกิจกรรมเพื่อเตรียมความพร้อมในการประกอบอาชีพ"
* #9009683 "Vocational rehabilitation training" "การฝึกกิจกรรมที่ใช้ในการประกอบอาชีพ"
* #9009684 "Home management training" "การฝึกการจัดการเพื่อเตรียมบ้านและที่อยู่อาศัย"
* #9009699 "Rehabilitative training, unspecified" "การฝึกทางด้านเวชศาสตร์ฟื้นฟูอื่นๆ, ไม่ระบุ"
* #9009701 "Home and environmental adaptation" "การปรับสภาพบ้านและสิ่งแวดล้อม"
* #9009702 "Home visit for rehabilitative care" "การเยี่ยมบ้านเพื่อการดูแลด้านเวชศาสตร์ฟื้นฟู"
* #9011714 "Skin pressure garment (scar treatment)" "ชุดผ้ายืดเพื่อกดรักษาแผลเป็นของผิวหนัง"
* #9021503 "Soft tissue stretching unspecified site" "การดัดยืดเหยียดเนื้อเยื่ออ่อน, ไม่ระบุตำแหน่งหรืออัวยวะ"
* #9028100 "Nerve and motor point block at nerve branches supply to unspecified muscles, using therapeutic agent" "การฉีดยาหรือสารยับยั้งกระแสประสาทที่สาขาเส้นประสาทหรือจุดเส้นประสาทสั่งการเชื่อมกับกล้ามเนื้อมัดต่างๆ, ไม่ระบุมัดกล้ามเนื้อ"
* #9028101 "Botulinum toxin injection" "การฉีดสารโบทูลีนัมทอกซินที่กล้ามเนื้อ"
* #9028102 "Trigger point release, using therapeutic agents injection, at unspecified muscles" "การสลายจุดกดเจ็บทริกเกอร์พอทย์ โดยการฉีดยาหรือสารเพื่อการรักษา ที่กล้ามเนื้อมัดต่างๆ, ไม่ระบุรายละเอียด"
* #9028103 "Trigger point release, using dry needle, at unspecified muscles" "การสลายจุดกดเจ็บทริกเกอร์พอทย์ โดยใช้เข็ม ที่กล้ามเนื้อมัดต่างๆ, ไม่ระบุรายละเอียด"
* #9028198 "Local injection with therapeutic substance in soft tissue" "การฉีดเฉพาะที่ด้วยยาหรือสารเพื่อการบำบัดรักษาเข้าในเนื้อเยื่ออ่อน"
* #9031504 "Muscle stretching unspecified site" "การดัดยืดเหยียดกล้ามเนื้อ ไม่ระบุตำแหน่งหรืออัวยวะ"
* #9031505 "Muscle stretching with coolant spray unspecified site" "การดัดยืดเหยียดกล้ามเนื้อด้วยสเปรย์เย็น, ไม่ระบุตำแหน่งหรืออัวยวะ"
* #9041506 "Tendon stretching unspecified site" "การดัดยืดเหยียดเอ็นกล้ามเนื้อ, ไม่ระบุตำแหน่งหรืออัวยวะ"
* #9131507 "Joint manipulation/play unspecified site" "การดัดยืดเหยียดข้อ, ไม่ระบุตำแหน่งหรืออัวยวะ"
* #9138100 "Local injection with therapeutic substance into joint" "การฉีดเฉพาะที่ด้วยยาหรือสารเพื่อการบำบัดรักษาเข้าในข้อต่อ"
* #9219611 "Cardiac rehabilitation for inpatient care" "การบำบัดรักษาและดูแลด้านเวชศาสตร์ฟื้นฟูโรคหัวใจสำหรับผู้ป่วยใน"
* #9219612 "Cardiac rehabilitation for outpatient care" "การบำบัดรักษาและดูแลด้านเวชศาสตร์ฟื้นฟูโรคหัวใจสำหรับผู้ป่วยนอก"
* #9219613 "Cardiac rehabilitation using EKG Telemetry Monitoring" "การบำบัดรักษาและดูแลด้านเวชศาสตร์ฟื้นฟูโรคหัวใจโดยใช้เครื่องส่งสัญญาน คลื่นหัวใจระยะไกล"
* #9232201 "Postural drainage for respiratory system without percussion or vibration technique" "การจัดท่าเพื่อระบายเสมหะสำหรับโรคระบบทางเดินหายใจ โดยไม่มีการสั่นหรือการเคาะปอด"
* #9232202 "Postural drainage for respiratory system with percussion technique" "การจัดท่าเพื่อระบายเสมหะสำหรับโรคระบบทางเดินหายใจ ร่วมกันการเคาะปอด"
* #9232203 "Postural drainage for respiratory system with vibration technique" "การจัดท่าเพื่อระบายเสมหะสำหรับโรคระบบทางเดินหายใจ ร่วมกันการสั่นปอด"
* #9232204 "Sustained maximum inspiration using incentive spirometer"
* #9239621 "Pulmonary rehabilitation for inpatient" "การบำบัดรักษาและดูแลด้านเวชศาสตร์ฟื้นฟูโรคปอดสำหรับผู้ป่วยใน"
* #9239622 "Pulmonary rehabilitation for outpatient" "การบำบัดรักษาและดูแลด้านเวชศาสตร์ฟื้นฟูโรคปอดสำหรับผู้ป่วยนอก"
* #9239623 "Breathing exercise training for respiratory problems" "การฝึกบริหารกล้ามเนื้อใช้ในการหายใจในผู้ป่วยที่มีปัญหาในการหายใจ"
* #9279601 "Oral-motor stimulation and training" "การฝึกกระตุ้นการเคลื่อนไหวกล้ามเนื้อในปากและคอ"
* #9279602 "Swallowing training" "การฝึกกลืน"
* #9289603 "Bowel training" "การฝึกการควบคุมขับถ่ายอุจจาระ"
* #9289604 "Bladder training" "การฝึกการควบคุมขับถ่ายปัสสาวะ"
* #9289605 "Pelvic floor training" "การฝึกควบคุมกล้ามเนื้ออุ้งเชิงกราน"
* #9330000 "Neurological assessment and evaluation" "การตรวจประเมินและการประเมินผลระบบประสาท"
* #9330200 "Nerve conduction study 1-3 nerves" "การตรวจการนำกระแสประสาทด้วยไฟฟ้าวินิจฉัย จำนวน 1-3 เส้น"
* #9330201 "Nerve conduction study 4-7 nerves" "การตรวจการนำกระแสประสาทด้วยไฟฟ้าวินิจฉัย จำนวน 4-7 เส้น"
* #9330202 "Nerve conduction study > 7 nerves" "การตรวจการนำกระแสประสาทด้วยไฟฟ้าวินิจฉัย จำนวน >7 เส้น (มากกว่า 7 เส้นขึ้นไป)"
* #9330203 "Repetitive nerve stimulation [Decrement test]" "การตรวจประเมินความล้าของกล้ามเนื้อด้วยการกระตุ้นไฟฟ้าซ้ำๆต่อมัด"
* #9330204 "Needle electromyography 1-3 muscles" "การตรวจบันทึกคลื่นไฟฟ้ากล้ามเนื้อด้วยอิเล็คโทรดชนิดเข็ม กล้ามเนื้อ 1-3 มัด"
* #9330205 "Needle electromyography 4-7 muscles" "การตรวจบันทึกคลื่นไฟฟ้ากล้ามเนื้อด้วยอิเล็คโทรดชนิดเข็ม กล้ามเนื้อ 4-7 มัด"
* #9330206 "Needle electromyography > 7 muscles" "การตรวจบันทึกคลื่นไฟฟ้ากล้ามเนื้อด้วยอิเล็คโทรดชนิดเข็ม กล้ามเนื้อมากว่า 7 มัด"
* #9330207 "Electromyography, using surface electrodes" "การตรวจบันทึกคลื่นไฟฟ้ากล้ามเนื้อด้วยอิเล็คโทรดชนิดแผ่นติดผิวหนัง"
* #9330210 "Quantitative electromyography"
* #9330211 "Single fiber electromyography"
* #9330212 "Somatosensory evoked potentials" "การตรวจการนำกระแสประสาทรับความรู้สึกจากประสาทส่วนปลายถึงสมอง"
* #9330213 "Intraoperative somatosensory evoked potential" "การตรวจการนำกระแสประสาทรับความรู้สึกจากประสาทส่วนปลายถึงสมองในห้องผ่าตัด"
* #9330214 "Brain stem auditory evoked potentials [Auditory evoked responses]" "การตรวจประเมินการนำกระแสประสาทรับรู้การได้ยินผ่านก้านสมอง"
* #9330215 "Autonomic responses [tests]" "การตรวจประเมินระบบประสาทอัตโนมัติ"
* #9330216 "Visual evoked potentials" "การตรวจประเมินการนำกระแสประสาทการมองเห็น"
* #9330220 "Motor evoked potentials using electrical stimulation" "การตรวจการนำกระแสประสาทสั่งการจากประสาทส่วนปลายถึงสมองกระตุ้นด้วยไฟฟ้า"
* #9330221 "Motor evoked potentials using magnetic stimulation at peripheral nerves" "การตรวจการนำกระแสประสาทสั่งการจากประสาทส่วนปลายถึงสมองกระตุ้นด้วยแม่เหล็ก"
* #9330222 "Motor evoked potentials using magnetic stimulation at spinal cord" "การตรวจการนำกระแสประสาทสั่งการจากประสาทไขสันหลังถึงสมองกระตุ้นด้วยแม่เหล็ก"
* #9330223 "Motor evoked potentials using magnetic stimulation at brain skin" "การตรวจการนำกระแสประสาทสั่งการจากหนังศรีษะถึงสมองกระตุ้นด้วยไฟฟ้า"
* #9330224 "Sensory testing using special equipment" "การตรวจการรับรู้ความรู้สึกโดยใช้อุปกรณ์พิเศษ"
* #9330299 "Neurophysiologic or Electrodiagnostic tests, unspecified" "การตรวจประเมินทางสรีระของระบบประสาทและกล้ามเนื้อด้วยไฟฟ้าวินิจฉัยอื่น, ไม่ระบุรายละเอียด"
* #9349641 "Neuro-developmental training" "การฝึกพัฒนาการทางสมองและระบบประสาท"
* #9349642 "Perception and cognitive training" "การฝึกการรับรู้และความเข้าใจ, กระบวนการคิด"
* #9349643 "Coordination training" "การฝึกการเคลื่อนไหวให้ประสานกัน"
* #9349644 "Dyslexia training" "การฝึกเพื่อรักษาภาวะเสียการอ่านรู้ความ"
* #9359645 "Sensory and motor training" "การฝึกประสาทรับรู้และประสาทสั่งการ"
* #9359646 "Sensory integration training" "การฝึกประมวลการรับรู้ความรู้สึก"
* #9371600 "Orthotic fitting" "การปรับแต่งกายอุปกรณ์พยุงให้พอดี"
* #9371610 "Prosthetic fitting for non-functional or cosmetic purpose" "การปรับแต่งกายอุปกรณ์เทียมเพื่อให้ดูมีอวัยวะอยู่ (ไม่สามารถใช้งานได้)"
* #9371620 "Prosthetic fitting, mechanical control" "การปรับแต่งกายอุปกรณ์เทียมชนิดมีกลไกที่ควบคุมได้"
* #9371621 "Prosthetic fitting, using electronic power and/or computerized control" "การปรับแต่งกายอุปกรณ์เทียมชนิดที่ควบคุมด้วยเครื่องไฟฟ้าหรือคอมพิวเตอร์"
* #9371630 "Assistive device prescription and fitting" "การเลือกใช้และปรับแต่งอุปกรณ์เสริมใช้ช่วยในการเคลื่อนไหว"
* #9371631 "Mobility aids prescription and fitting" "การเลือกใช้และปรับแต่งอุปกรณ์ใช้ช่วยเดินและการเคลื่อนที่"
* #9371699 "Other functional device prescription and fitting, unspecified" "การเลือกใช้และปรับแต่งอุปกรณ์เสริมช่วยในการเคลื่อนไหวอื่นๆ, ไม่ระบุรายละเอียด"
* #9375811 "Passive range of motion (PROM) exercise" "ออกกำลังกายบริหารเพื่อคงพิสัยของข้อที่ไม่ได้ทำเอง/มีคนทำให้"
* #9375812 "Passive range of motion exercise, using PNF or other special techniques" "ออกกำลังกายบริหารเพื่อคงพิสัยของข้อที่ไม่ได้ทำเอง โดยเทคนิควิธีพีเอนเอฟ หรือเทคนิควิธีอื่นๆ"
* #9375813 "Passive range of motion exercise, using continuous PROM machine (Continuous Passive Motion)" "ออกกำลังกายบริหารเพื่อคงพิสัยของข้อด้วยเครื่องบริหารแบบต่อเนื่อง"
* #9375814 "Passive stretching, manual" "ออกกำลังกายบริหารเพื่อเพิ่มพิสัยของข้อด้วยการดัดยืดเหยียดที่ไม่ได้ทำเอง"
* #9375815 "Active assisted ROM exercise" "ออกกำลังกายบริหารเพื่อคงพิสัยของข้อด้วยตัวเองที่ต้องช่วย"
* #9375816 "Active assisted ROM exercise, using PNF technique" "ออกกำลังกายบริหารเพื่อคงพิสัยของข้อด้วยตัวเองที่ต้องช่วย ด้วยเทคนิควิธีพีเอนเอฟ"
* #9375817 "Generalized conditioning exercise using equipments" "ออกกำลังกายบริหารเพื่อปรับสภาพทางกายโดยทั่วไปด้วยเครื่องมือหรืออุปกรณ์"
* #9375818 "Generalized conditioning exercise not using equipments" "การออกกายบริหารเพิ่มสมรรถภาพโดยทั่วไปโดยไม่ใช้อุปกรณ์"
* #9375819 "Resistive/strengthening, using isometric exercise" "การออกกำลังกายด้วยอุปกรณ์เพิ่มแรงต้านชนิดไอโซเมตริก (ความยาวกล้ามเนื้อคงที่)"
* #9375820 "Resistive/strengthening, using isotonic exercise" "การออกกำลังกายด้วยอุปกรณ์เพิ่มแรงต้านชนิดไอโซโทนิค (แรงต้านคงที่)"
* #9375821 "Resistive/strengthening, using isokinetic machine" "การออกกำลังกายเพื่อความแข็งแรงของกล้ามเนื้อด้วยอุปกรณ์เพิ่มแรงต้านชนิดไอโชไคเนติค (ความเร็วคงที่)"
* #9375822 "Exercise for Aerobic capacity, using treadmill" "การออกกำลังกายเพิ่มความสามารถด้านแอโรบิค โดยใช้ลู่วิ่งเทรดมิลล์"
* #9375823 "Exercise for Aerobic capacity, using ergometer device" "การออกกำลังกายเพิ่มความสามารถด้านแอโรบิค โดยใช้เครื่องปั่นด้วยแขนหรือขา"
* #9375824 "Exercise for Aerobic capacity, using others or unspecified" "การออกกำลังกายเพื่อเพิ่มสมรรถภาพด้านแอโรบิคด้วยวิธีอื่นๆ หรือ ไม่ระบุรายละเอียด"
* #9375825 "Aquatic/water and pool exercise" "การออกกำลังกายเพื่อการบำบัดรักษาในน้ำ"
* #9375899 "Other therapeutic exercises, unclassified" "การออกกำลังกายเพื่อการบำบัดรักษาด้วยวิธีอื่นๆ, ไม่ระบุรายละเอียด"
* #9375911 "Electrical stimulation (ES) to retard muscle atrophy at unspecified site" "การบำบัดรักษาด้วยเครื่องกระตุ้นไฟฟ้า เพื่อลดกล้ามเนื้อลีบ"
* #9375912 "Electrical stimulation (ES), using Interferential ES device at unspecified site" "การบำบัดรักษาด้วยเครื่องกระตุ้นไฟฟ้าแบบอินเตอร์เฟอเรนเชียล"
* #9375913 "Transcutaneous electrical nerve stimulation (TENS)" "การบำบัดรักษาด้วยเครื่องกระตุ้นไฟฟ้าเพื่อลดปวดผ่านผิวหนัง"
* #9375914 "Electrical stimulation (ES) for iontophoresis" "การบำบัดรักษาด้วยเครื่องกระตุ้นไฟฟ้าด้วยการผลักดันประจุไฟฟ้า"
* #9375915 "Functional electrical stimulation (FES)" "เครื่องกระตุ้นไฟฟ้าเพื่อช่วยควบคุมการเคลื่อนไหว"
* #9375916 "Pudendal nerve stimulation" "การบำบัดรักษาด้วยเครื่องกระตุ้นไฟฟ้าเส้นประสาทพลูเดนดอล"
* #9375917 "Intravesical electrical stimulation" "การบำบัดรักษาด้วยเครื่องกระตุ้นไฟฟ้าที่กล้ามเนื้อกระเพาะปัสสาวะ"
* #9375999 "Other electrical stimulation (ES) device, unspecified" "การบำบัดรักษาด้วยเครื่องกระตุ้นไฟฟ้าอื่นๆ, ไม่ระบุรายละเอียด"
* #9379653 "Biofeedback training" "การฝึกด้วยอุปกรณ์ไบโอฟิดแบค"
* #9379654 "Ambulation, transfer and gait training, general mobility" "การฝึกการเคลื่อนที่, การย้ายตัวและท่าเดิน, โดยทั่วไป"
* #9379655 "Ambulation, transfer, wheelchair mobility" "การฝึกการเคลื่อนที่, การย้ายตัว, โดยใช้รถเข็น"
* #9379656 "Ambulation, transfer and gait training, on parallel bar" "การฝึกการเคลื่อนที่, การย้ายตัวและท่าเดิน, ฝึกในราวขนานช่วยยืนเดิน"
* #9379657 "Ambulation, transfer and gait training, using gait aids or assistive devices" "การฝึกการเคลื่อนที่, การย้ายตัวและท่าเดิน, ฝึกด้วยอุปกรณ์ช่วยพยุงเดินชนิดต่างๆ"
* #9379658 "Ambulation, transfer and gait training, not using gait aids or assistive devices" "การฝึกการเคลื่อนที่, การย้ายตัวและท่าเดิน, ฝึกโดยไม่ใช้อุปกรณ์ช่วยพยุงเดินชนิดต่างๆ"
* #9379659 "Ambulation, transfer and gait training, LE prosthetic training" "การฝึกการเคลื่อนที่, การย้ายตัวและท่าเดิน, โดยใส่ขาเทียม"
* #9379660 "Orthotic training, upper extremity" "การฝึกการใช้อุปกรณ์ช่วยพยุงของแขน (ระยางค์บน)"
* #9379661 "Orthotic training, lower extremity" "การฝึกการใช้อุปกรณ์ช่วยพยุงของขา (ระยางค์ล่าง)"
* #9379662 "Prosthetic training, upper extremity" "การฝึกการใช้อวัยวะเทียมส่วนแขน (ระยางค์บน)"
* #9379663 "Prosthetic training, lower extremity" "การฝึกการใช้อวัยวะเทียมส่วนขา (ระยางค์ล่าง)"
* #9379664 "Adaptive device training" "การฝึกการใช้อุปกรณ์ปรับช่วยในเคลื่อนไหว"
* #9381710 "Strapping and taping" "การพันเทปเพื่อตรึงข้อ"
* #9409671 "Auditory training" "การฝึกการได้ยิน"
* #9409672 "Speech defect training" "การฝึกเพื่อรักษาความผิดปกติหรือบกพร่องของการพูด"
* #9409673 "Esophageal speech training" "การฝึกการพูดทดแทนด้วยการใช้หลอดอาหาร"
* #9409674 "Breathing exercise training for speech therapy" "การฝึกการหายใจเพื่อการรักษาด้านอรรถบำบัด"
* #9409675 "Language defects training (dysphasia, dysarthria, etc.)" "การฝึกเพื่อรักษาความผิดปกติในการใช้ภาษาพูด (พูดบกพร่อง, พูดไม่ชัด)"
* #9409676 "Language training in visual disorders" "การฝึกภาษาสำหรับความผิดปกติในการมองเห็น"
* #9409679 "Other speech and language training and therapy, unspecified" "การฝึกภาษาและการพูดอื่นๆ, ไม่ระบุ"